# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e807ad22186bb47b5c346ff7cf9e4aa81b3785ed6fa031f4a709c7897661a7cc5ffdbdf9da57c80a525d5d5680f495d82a90172942143a256dfc82817b37c81f

test:
  secret_key_base: ae345a802b3643b0845939781530f956f39f98d8268164bef229eb7a3980d6db7588cc0b0a2972d7007fe9efbac13cf96835ad106677d04a0504531231414483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
